### ISSUE TITLE
Structure of ctf.pkl

### ISSUE THREAD

**Issue by bwmr** [ml-struct-bio/drgnai#3]
Hi, 

I'm excited to test out drgnai, but I could not find any information on how the required CTF-parameter pickle file should be structured / which information it should contain. 

Are there parsers available to create the file automatically, based on the information in the `particle.star` from relion?

Thanks in advance,
Best,
Benedikt

**Comment by WenZhng** [comment]
`$ cryodrgn parse_ctf_star particles.star -D 300 --Apix 1.03 -o ctf.pkl`

**Comment by bwmr** [comment]
Fantastic, thank you!
