### ISSUE TITLE
Missing f for f-string while lazy loading

### ISSUE THREAD

**Issue by sholalkere** [ml-struct-bio/drgnai#5]
[Logging the dataset statistics while lazy loading](https://github.com/ml-struct-bio/drgnai/blob/main/src/dataset.py#L165) appears to be missing the f require to make it an f-string.
> `logger.info("Lazy loaded {len(particles_real)} {ny}x{nx} images")`

**Comment by michal-g** [comment]
Yup thanks for the catch, will be fixing this shortly!
